# Generated by Django 2.1.3 on 2018-11-12 08:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=256)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('took_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(null=True)),
                ('uploaded_by', models.UUIDField()),
                ('county', models.CharField(max_length=15)),
                ('district', models.CharField(max_length=15)),
                ('road', models.CharField(max_length=75)),
                ('verified_amount', models.IntegerField()),
                ('is_board', models.BooleanField()),
                ('price', models.IntegerField(blank=True, null=True)),
                ('receipt', models.CharField(max_length=256)),
                ('not_board_amount', models.IntegerField()),
                ('note', models.CharField(max_length=512)),
                ('candidates', models.ManyToManyField(to='candidates.Terms')),
            ],
        ),
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(max_length=128)),
                ('is_board', models.BooleanField(blank=True, null=True)),
                ('created_by', models.UUIDField()),
                ('created_at', models.DateTimeField()),
                ('type', models.IntegerField()),
                ('headcount', models.IntegerField()),
                ('is_original', models.BooleanField()),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='boards.Boards')),
                ('candidates', models.ManyToManyField(to='candidates.Terms')),
            ],
        ),
    ]
